Converting HTML Readme to Markdown
podofo/podofo pull request #11
Opened 2022-10-17 11:17 UTC by KunalGehlot

This is to make the project more accessible to Github users.

Issue: #10

2022-10-17 11:20 UTC, KunalGehlot commented
Please note that the contents of the README have **not** been altered except for a few broken internal links while converting to markdown.

2022-11-29 11:51 UTC, ccreutzi requested changes
This is a great improvement, thanks for the PR. If you're willing, I'd like to ask for a few more tweaks before merging. In particular, the code blocks are currently formatted as running text without their line breaks, I tried to mark all of them.

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> +  - [PoDoFo](#podofo)
These two lines seem unnecessary, can we just remove them (and ideally move the other lines to the left)?

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> +PoDoFo is available on the internet: [podofo.sf.net](http://podofo.sf.net)
I appreciate not mixing the format transition with content changes, but we probably want to point at https://github.com/podofo/podofo/ now.

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> +If your project uses STLPort rather than your platform/toolset's native STL, you must configure PoDoFo to use STLPort as well. Use the -DUSE\_STLPORT=1 argument to configure. Do not enable STLPort fo
Should -DUSE… be in backticks?

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> +PoDoFo can make limited use of the Boost libraries if they are available. There is no need to use them, but some things may work more smoothly, and more use is expected in the future. If PoDoFo is bu
Should -DWANT… be in backticks?

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> +All instructons below use out-of-tree builds (recommended). To clean up an out-of-tree build, just delete the build directory, as no files are touched within the source directory.
Typo: instructions

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> +
code block, should have ```

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> +make VERBOSE=1
code block, should have ```

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> + -DCMAKE\_LIBRARY\_PATH=/usr/sfw/lib
code block, should have ```

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> + -DPODOFO\_BUILD\_STATIC:BOOL=FALSE
code block, should have ```

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> +/opt/local/bin/port install fontconfig freetype jpeg tiff lua
code block, should have ```

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> + make install
code block, should have ```

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> +make install
code block, should have ```

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> +.
Both of these look like the full stop/period should be part of the preceding paragraph.

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> +.
Looks like the full stop/period should be part of the preceding paragraph.

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> + -DPODOFO\_BUILD\_SHARED=FALSE
code block, should have ```

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> +- ZLIB\_LIBRARY\_NAMES\_DEBUG, ZLIB\_LIBRARY\_NAMES\_RELEASE, ZLIB\_LIBRARY\_NAMES
These should be in backticks, I believe.

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> +mingw32-make
code block, should have ```

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> +cmake -G "Visual Studio 9 2008" ..\\podofo-src -DCMAKE\_INCLUDE\_PATH="%FTDIR%\\include;%JPEGDIR%\\include;%JPEGDIR%;%ZLIBDIR%\\include" -DCMAKE\_LIBRARY\_PATH="%FTLIBDIR%;%FTDIR%\\lib;%JPEGDIR%\\lib
code block, should have ```

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> +set PATH=%SystemRoot%;%SystemRoot%\\SYSTEM32
code block, should have ```

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> +    -lpodofo -lfreetype -lfontconfig -ljpeg -lz
code block, should have ```

2022-11-29 11:51 UTC, ccreutzi commented on README.md
> +Indicates a debug build of PoDoFo.
The formatting isn't great. I'd suggest we at least leave out the (pseudo-)headers, and ideally would use a [definition list](https://www.markdownguide.org/extended-syntax/#definition-lists).

2022-12-28 21:20 UTC, ceztko commented
I just merged the PR with Christopher suggestions, thank you. I would like to add that while this work is very welcome, I can't guarantee I will spend enough time on integrating the content from here when pushing [pdfmm](https://github.com/pdfmm/pdfmm) (which already had a Markdown readme) into PoDoFo. Also in a sense this README is too much verbose for today standards, so we'll see. Anyway it's a very useful work and it will be easier to source from here once PoDoFo-next is up.

2022-12-28 21:20 UTC, closed without merging