fix tools build for mingw
podofo/podofo pull request #155
Opened 2024-04-17 09:06 UTC by ognevny

add `-municode` LDFLAG for `WinMain` symbol. IS NOT related to #152

- [x] Accept to license the library and tools code under the terms
  of the [LGPL 2.0](https://spdx.org/licenses/LGPL-2.0-or-later.html) or later
- [x] Accept to license the library and tools code under the terms
  of the [MPL 2.0](https://spdx.org/licenses/MPL-2.0)
- [x] Accept to license the test code under the terms
  of the [MIT-0](https://spdx.org/licenses/MIT-0.html)
- [x] Read [contributions](https://github.com/podofo/podofo#contributions) guidelines
- [x] Checked coding [style](https://github.com/podofo/podofo/blob/master/CODING-STYLE.md)
- [x] The commits sequence is clean without work in progress/bugged revisions and merge commits. In doubt, [squash](https://github.com/podofo/podofo/wiki/Squash-git-history-guide) the commits and/or rebase master

2024-05-04 09:49 UTC, ceztko requested changes
Sorry for the delay. The test for MINGW must be in the else() branch, not as elseif() of MSVC. Just put the if(MINGW)/endif() in the else() branch.

2024-05-04 10:09 UTC, ognevny commented
> Sorry for the delay. The test for MINGW must be in the else() branch, not as elseif() of MSVC. Just put the if(MINGW)/endif() in the else() branch.

ok, will do. but I'm currently on vacation until tomorrow

2024-05-05 14:54 UTC, ognevny commented
> Sorry for the delay. The test for MINGW must be in the else() branch, not as elseif() of MSVC. Just put the if(MINGW)/endif() in the else() branch.

done

2024-05-05 15:02 UTC, ognevny commented
now (with this change) podofo lib+tools succesfully builds for clang, but lib only for gcc
error:
```
FAILED: target/podofobox.exe
C:\WINDOWS\system32\cmd.exe /C "cd . && C:\msys64\ucrt64\bin\c++.exe -Wall -Woverloaded-virtual -Wswitch -Wcast-qual -Wwrite-strings -Wredundant-decls -Wreorder -Wno-format-truncation -Wno-unknown-pragmas -Wno-unknown-warning-option -municode tools/podofobox/CMakeFiles/podofobox.dir/boxsetter.cpp.obj tools/podofobox/CMakeFiles/podofobox.dir/podofobox.cpp.obj -o target\podofobox.exe -Wl,--out-implib,target\libpodofobox.dll.a -Wl,--major-image-version,0,--minor-image-version,0  target/libpodofo.dll.a  target/libtools_private.a  target/libpodofo_private.a  C:/msys64/ucrt64/lib/libssl.dll.a  C:/msys64/ucrt64/lib/libcrypto.dll.a  C:/msys64/ucrt64/lib/libfontconfig.dll.a  C:/msys64/ucrt64/lib/libfreetype.dll.a  C:/msys64/ucrt64/lib/libxml2.dll.a  C:/msys64/ucrt64/lib/libpng.dll.a  C:/msys64/ucrt64/lib/libtiff.dll.a  C:/msys64/ucrt64/lib/libjpeg.dll.a  C:/msys64/ucrt64/lib/libz.dll.a  -lkernel32  -luser32  -lgdi32  -lwinspool  -lcomdlg32  -ladvapi32  -lshell32  -lole32  -loleaut32  -luuid  -lws2_32  -lCrypt32  C:/msys64/ucrt64/lib/libidn.dll.a  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: target/libtools_private.a(MainEntryPoint.cpp.obj):MainEntryPoint:(.text+0x24c): undefined reference to `PoDoFo::PdfError::what() const'
collect2.exe: error: ld returned 1 exit status
```

2024-05-05 16:53 UTC, ceztko commented
Then I guess you can do `if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND MINGW)`, still within the else() branch.

2024-11-12 08:05 UTC, ognevny commented
what's blocking for this change now?

2024-11-12 09:07 UTC, ceztko commented
Possibly at the time I misunderstood the error in this [comment](https://github.com/podofo/podofo/pull/155#issuecomment-2094842975) and expected further modifications. I'm merging, let's see what happens.

2024-11-12 09:08 UTC, ceztko approved these changes

2024-11-12 09:08 UTC, merged